#spring:
#  datasource:
#    # 动态数据源配置
#    dynamic:
#      datasource:
#        master:
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://192.168.1.222:3306/user_db?useUnicode=true&serverTimezone = GMT
#          username: root
#          password: hell@@##8793FDSF
#      # 指定默认数据源名称
#      primary: master
#      seata: true
